hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "36ffd9dc085d529a7e60e1276d73ae5a030b020313e6c5408593a6ae2af39673"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "438de2af36bf905993252e5015ad3b2f907473f0ad2722d6c79185728bb9b20b"

[[files]]
file = "config/modmenu.json"
hash = "bb0fd753f16b39638ef004c9e5c29fdce0baae48edc6c2e06715955215d6418a"

[[files]]
file = "config/particular-common.toml"
hash = "dc1572f3bf075ee5d24fa5c0e1e9b1efacc88e3a430ec46a392a3039e019047a"

[[files]]
file = "config/pickupnotifier-client.toml"
hash = "6e1c4484678844870d0f657db537bc17469743c5d6f03fe916046c4b125a7361"

[[files]]
file = "config/sodium-extra-options.json"
hash = "d303add15bb337e4135210aa5361ab843b56988e6f73a7e621b095570b558fb0"

[[files]]
file = "configureddefaults/config/autofish.config"
hash = "024cbcf1b123bb71fd1fac439eebf840474cd0a0834c5ca291732c158501fc3d"

[[files]]
file = "configureddefaults/config/durability-viewer.json"
hash = "a8d9c56a0ba8528d68137d4a46a0d9936fc21fd03fd3ff35499e30f073c3ff0a"

[[files]]
file = "configureddefaults/config/effecttimerplus.json"
hash = "963a947c9c76a2e8de974e31855c280723e01733fa7e5fbbaa1b51914e279ca0"

[[files]]
file = "configureddefaults/config/elytrapitch.toml"
hash = "5e8fb93e294dc46c88d79b4f372f28e308b0d58f1e399da4953cbbac97133c80"

[[files]]
file = "configureddefaults/config/shulkerboxtooltip.json5"
hash = "db85ba235510d022acd24965041a966b24ee36a319668deb8e2c867ffbae8fac"

[[files]]
file = "configureddefaults/config/xaerominimap.txt"
hash = "19fb405ae338ec764fbaf37b4320de14bedbca1dccd290e5abbf9bd12ded4ab8"

[[files]]
file = "configureddefaults/options.txt"
hash = "9ff867846a1c0d96efc7d4077f7bc77a32741ca1585add8af596fe785f34c24a"

[[files]]
file = "configureddefaults/servers.dat"
hash = "63c5cd5854a04c03f74a29c7cf6de37b4cf77a84f30e46ed1c4a6ad68d574689"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "c71213885593728467f9063ac63c1ba54912732a243a3d1c30f809bcc014d166"
metafile = true

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "5d1b0d0fc0c0422d25b54e0bd7a76a7733967278c7691830fb53fb0879ad4884"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "38ce16b25494d653eab2e575e9944df3fd07906ef0dc548562e4e010377a6f4f"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c22ebc9646c063a5c53acae5b49a0b54f8b21500ecc79a9c52b142775512b2d6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "832691489ab19e2f0a4b81b77c143a8dceb5f3f395cdee96bcddd893fb01b363"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "220695895a8fd68ca82b7b3c34d8499b4f6ea73f6588e3dfbccd2307af0b924d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "e15eb47019c1372379817862e66999aa3eb4dedc5661fae902147b15201c8054"
metafile = true

[[files]]
file = "mods/better-animations-collection.pw.toml"
hash = "40886617a6f2dbc6b8aa9d3ad1237c65f09cafd454ba6bc99c73cbfe21846a9a"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "841012fc0e455651bb637434bce2b0d66f74e4cd16e35a055c6ce3b655f72a74"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "74c01cc05241bb689fbb6bb7a26aebb4897b272fdbbf33f57c04fc453bfa75eb"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "2d1c297c06a8781464a18d28d4a6d5c4807d216e42f6e315215d244ecdcb254b"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "2da7cdeb19a0a1466547c544d0e9b0e80828d129e22ce1497256bdf6cf6d51e5"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "9b5595b414f281b4f30c53751d0a0fb213ea4e70b94baf3e249886585f1afefb"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "e35cfde6ff15ff840e5a66ffc8cae03038815967b0036ade39ae1c4ad61f4619"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "56fc22a9f3dc3eb2aa598aad649071f84c43c17d8618a39f52aede94d29c0a1f"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "2108a3f7ff334130bc04e57cb19d56a6f0c1b403e89c120402e06dfb6c973412"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "e166ff1288ee8d45566269f867025ae16934284d592e7efac97d31596413b15f"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "aa27043c1c479a7ea833ac042e93ffb69af8c30e126b7916f960cc28697d5f4c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "71a28f3d54e0f7fbeec1a48bcaee5ee5ca9257939e8bfd8973721b9843b22f1d"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "c060b83f6c513649e38659d2edac8b364831a541f7767807708dc65f5bb836f3"
metafile = true

[[files]]
file = "mods/connected-doors.pw.toml"
hash = "cae5a2115a7bdf52e8d4cbbcd03486a1e71d8cb04ba9940e8852849d146c9da1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a86751e4931b83d8f3de8e84e38f2dc0aa316e40c99b9e9f03a9276659a474b6"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d264afb5412f6f8e12d7ce75b4bfc8c752a5c41e520059593d583ce2e3490077"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "5c21bc7913dcfeeebf37acd986bccac4dc93a9dc712cda3d7ea1be0ea868211a"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "e5cf907d7bc2c5154e007185f305e575acd9faec6718d30e61a77fa81b92d3b5"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "554190499d5711421a831f95c777b85d2592482dfee9d5014580b8feef2f592a"
metafile = true

[[files]]
file = "mods/csearcher.pw.toml"
hash = "9a2a457ce9822ea63a8576b67dd965bb97fc6ea0f272077aef3f9b48ac9e3e62"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "12804ce02e8891b9c55bf25bc4df8273b3dfcafa7a2c91b055b3836359e84e7c"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "937acae581d8c4340d141446a7adb5b3b1915130fd483bee067d45aade834a8a"
metafile = true

[[files]]
file = "mods/deimos.pw.toml"
hash = "ab03ae9815a9d5b58ad46d589d4a6e5eddaae2dfc03b1c38e5290ecc439bfbd6"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "0d07adf7d0d94bb683d412849b363f0e770d77ce0808414e2080e4ae773dde7d"
metafile = true

[[files]]
file = "mods/dnp.pw.toml"
hash = "8cdd58be17fcf26dffc6f4091314a9c129c8019d160793abafafac72fc0bfcf3"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "4e230e35117c08a4f63428b6b1d62b1e6d14542ccf91396dc4fbc98527c51db4"
metafile = true

[[files]]
file = "mods/durability-viewer-updated.pw.toml"
hash = "7fd7a173552cbf5aa1d1ad49293c4645dcd84b68743d523cf3ce2b60bc862051"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7ade9694388d80def1aba6b3653a1a0ea8a68eb14a42e2bffd076fd1335a5ce8"
metafile = true

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "7c8674fd64a05074cb56609b08da2fa2db965a075e454c9dc476c501e2cfc626"
metafile = true

[[files]]
file = "mods/elytra-physics.pw.toml"
hash = "aeb55f8c77cb7076cc695b0c8e1599c1bcf7bd95c563f83e6007ab08205b0e08"
metafile = true

[[files]]
file = "mods/elytrapitch.pw.toml"
hash = "8e175a2ff5832dda778fe94ad2f6630167231a3b6681ec2771798c56900673c5"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "3601d48216e7230ca91a366591d3d2ba8ad6e45cd7e0663f5e90410e0866c054"
metafile = true

[[files]]
file = "mods/enchantment-level-cap-indicator.pw.toml"
hash = "15cc2c0e37ba128731913e71ea53af65ac3d87223980eaea9596214bad5248d1"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a409a13d5f8bb087ff615dc5947b3f26c6bacec22618d8d733d8d4789fb3543"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ff166f6f205e4ce227da6fd173e45a8277730137f75f13fa0c47559745105637"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "84f74d4abc0ece0ed9f62d9454d35415ace97e0aa83ed3e8a2d1ff7167b45999"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "e56fa453beca9926d55a91b3687c814dfdce651419a455797cc3469e7c3ad7b1"
metafile = true

[[files]]
file = "mods/exp-counter.pw.toml"
hash = "efd8a9683ab23c1759de33752ebcd89009f563fe6fea161af2c2ad983a75d4c7"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "34684bd591ae5703edcbebe92b4066e7ff0365977a2fb804645644151d1b025c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "dae294bc7e60c5052b3c705bc15e4b2ebc1af7465e294c4f9824a4b63719475b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/fishing-ruler.pw.toml"
hash = "9027040e49bb281381f9d9fe2da76f381032f6bbc64aa248b7a4dbcb6adc990c"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "f0b705b810fc48523a67a90f218ae8085206b08421e2a006561169bf2847a907"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "2df76fcc5bacce682495502f342be0c1f74a33bf0835d80dd0d3d5fc0d2f3b19"
metafile = true

[[files]]
file = "mods/fuel-info.pw.toml"
hash = "0d58bce3c862bd187f95b25d916d7efb0a16db0bae3ccf5d5fecac8fa1ebcbe9"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "21c99b7589bf18a764a52327f29cc898846dbc4b2a714fec5694f69e1468da71"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9af4574f848b49a2b11822e81500aebacdb77c416dbcf4502be5feaabfb5f66f"
metafile = true

[[files]]
file = "mods/immersive-ui.pw.toml"
hash = "42f43d0eca9aff401dfb9f0028ec074b25ad1df387bba589b02b0af3f26f8a5c"
metafile = true

[[files]]
file = "mods/immersivethunder.pw.toml"
hash = "011bcff72011c872583d9ec9c1662267b36c53c14264f50305a2681ca8272d12"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "6685f10edcc37f4b78c13c08b82ab8ee0920a3b41cb832a5483682987dd1697d"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "8d40436970d9adcfe3c0b72c9f0cd1af217948469b091b0f07ca3df187ce2e61"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "329520ce48d8748fc7ff3a385aa9fb63848602ef79d598e51903ced4d3ecbc00"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e5506cea71f62e147a45e6c72a55a430fce5937024f648c819c15dc14b500462"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "edad218cc48e1fb4c78878ff4a7aec2810d6d647e59eefa1e86477f553f5d8c0"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "97385bd886d2fcad952fd7e76501300049237ec4a47a7b0240cf46138d9cc35a"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "bde1e584be6e389eb05cd4c113741f50798fe70e08cfb5c8cf487db6a6559dcb"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "e272c03ee9f508fb87884e93f049d62a495a338130a1f183373cca5cc8d04edc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a63765eb780a36cd968e2777d2c20bea5e5ca3ccdd920e64964e3746cf2a7f0d"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "20c255825398a46f84c92ea570ba3aa8c737f63dec886b2edc5739e969777f04"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "1d19237dc3a66d87a018bafb3f69e701bcba8ba1fdef71d9a5f17222c15a3120"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "e211f2d9ee543b916ac3e6492ee362deabb2534851c70faa3002b40a24bbd72b"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6eea5e1db3dbca126b82f211bf0d2fcf2cf13097023fdef3dd668e48581a73d0"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d122f53efcfd54e24ef7e15247bbebe788d4ea475c2f5b84ccc1254dc625a1ec"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "67d7d0cd20e2933d7b2a305d60e109bc6db868883209416ccfe5e22de281c1da"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "7d2683daeeea4990fe3e7e84443330cf36fa7732b577c050b1e9cec813eb3f5e"
metafile = true

[[files]]
file = "mods/my_totem_doll.pw.toml"
hash = "d5c8a515987ea81c2e8eb838b01cd027e0b743269e17589ec7bfa16ea8e295e2"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "85fe187b2b5df41af3dbdea2ffa8505c2d0f0507d8f4d6bc88621d038fceee62"
metafile = true

[[files]]
file = "mods/nether-coords.pw.toml"
hash = "2e527f2323d5a979d062cd5bdb4624fbab7a95b7b308944f8fc9a2906842d21d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "1b4530e79094030db3fcf262af621e5ebfb5036f70dfc39c3a2c9010357ceb0d"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "1c4197e0de54f02a03e5f43a4e17d72d0197186d83418fcee6a3632622a4a612"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "27bf21267ffb04d59ff52404aad040bd5cf95ca90701ede8f240ce033dafa927"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "aaa113528d488df3744621e67362de6b2db57116109256b06277974127007a28"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "bbcf3ad28288df3009f28bc2a3ecfcdb8f6d161c2679eaa6a79575c9619e897f"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "92f712374ae7c661137f8dc3bef752c247c9e63384faadc34c4b87c1a9c70a85"
metafile = true

[[files]]
file = "mods/perception.pw.toml"
hash = "f2fc56843bfd8788da8f410c21018197ed9932319ec6eebcb3eafa6eb35a81e0"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "70fa6e96fce494bff20cad6f5f6b2384065664e262ac66f424cffcd6eb5ea5c2"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "0993352e081593fca386a8a4e6473ece541a27e018c8384239f27f79d73133a0"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "5dff8bca658ae787c75fd2a37a40c8512a5fbc8a2421d106f94e08c8640b9075"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "ac443d194974caf238a5f976670ab47aa5f34073c8037bffb257c9d1498394d9"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "6d9742689a524965f89b5cb1194e4422f2454911a026fd9e98dce82db4a12157"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4019dc9d377028099ae87ffc5b03bd09deb284057a1e3b8910171837b2966266"
metafile = true

[[files]]
file = "mods/quick_hotkeys.pw.toml"
hash = "1deb6e3176f92f1972329a6964a4d58f7e658404194b59cb7a7e4f85d945d245"
metafile = true

[[files]]
file = "mods/real-arrow-tip.pw.toml"
hash = "426f585565aad4e89a397a2958cfb8e2d841be78cf253a3430bbfb5a27952e5f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "88f9a71bf06f4959b220abab8542e4763747903e9e5ef150c38ae79c83870077"
metafile = true

[[files]]
file = "mods/replanter-plus.pw.toml"
hash = "ca46cb65da179f2ad17f067ab9365a3091c33f93b8c5c34f6ab04d29cb58e29e"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "75d11a0b32a9fb7cd1235cc7ff3708e9acfe87fb0f07daca2764bb61723b78d8"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "17f1f78051aab0bb1b9855f9756ca41fe14aaefcedd8a3b772d8a9619d675794"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "f316a724cd4c3536d386a40387942f133954f3c57a871493fb8755e78e4546f4"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "1a563f0c589aced8101bb8a283af3725eedd1caaaaed4eb1987edfe3ff31c948"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "d11b1975a28e010204fd794db4d7c99c877fc93f9c229044fc7266c5ff61dfc5"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "4d05236df474f5934319258ddbbc7b2b4c0969fd7d872c1627d9b251e157507b"
metafile = true

[[files]]
file = "mods/slot-cycler.pw.toml"
hash = "5f99e6e1bfea3f2dcc2c3057ea14aa817ac0d6bd8302214b5779439c9bf5ef0b"
metafile = true

[[files]]
file = "mods/smart-completion.pw.toml"
hash = "e63cbc391d8157891d5a19cdbe617bfa6f14b1696ef6256cd6983d9d96ea80a0"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "b1f6b652c98f6b02f2f3435be7b51f999ab96a125fe482057a32aaefa0a1ee88"
metafile = true

[[files]]
file = "mods/smootheez-config-lib.pw.toml"
hash = "f7a0c030797c95cd92d5cdb57c2c4310b1575ad6bed5715609afa4e849eaa88c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b182456aefe4b8f37cc3dd34fdccbd07fcd0a2e9a6c175d5e39cd6d5190388dc"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "780646258386fccb6c92851e13dfb32b5d85cae9596ce6c829894b179245e64c"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "d3da75c483f2d3b89ac5ce8ab24258412dc21d52014d146bbd4b6eae842a3b24"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "eb8174f1f5671399d4f057451e8425b4996577ea4534c39d88e573e13ecd3e0a"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "7c07f85a7d89dbe99b3b00a633610264f6f83fc2a3d6a6ae8b1ceb82a0de3028"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "a6948eb25808d55a8dc3b9a64999181ebae738c3679ced2981c7c1ec34b9b0b6"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "d572ff6e626cbfa217511f976b258c5716571876779eff3f24a65bd397e49f6b"
metafile = true

[[files]]
file = "mods/toggle-item-frames.pw.toml"
hash = "c5587d6e7913642c627868b588ec0c034de9a46e749b512b041bc664aa685b3a"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "db3322e6f547044afc3f1ee13c49245244e080e29d128c6e6f6b1df613c8020c"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "989b6c4ff3dc08d7994667b4dfc9931a3b15876eabe4f9de7be8939153bb1fdc"
metafile = true

[[files]]
file = "mods/x+-autofish.pw.toml"
hash = "b7b2d44d458775763bfeff592433f2e04cf15f9aa4858c850bd7357baf6a9e6a"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d72a8ffcacdd19e6d71eccb4b112cf763bf75b2c438506e01ab0aa76e91c6325"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ea0eb6ab539b43926503901694913866aa81a9a644cd3469080214a7ca785db2"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "59e45ade7176229ff9750ae85356ba4a92b5124592dd09b0244c861cfda08575"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "028c0c4eb8e7f76ee32ba6889bae9c058da066c049d2e3e6c1172f84f9f1c134"
metafile = true

[[files]]
file = "resourcepacks/mace-but-3d-resourcepack.pw.toml"
hash = "91095494d12f6c730bdda405485bac57398071c110d217d2633852eb199ff022"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "d36d0104f40c65ec6e8f7b37c33662ebe57f06e1c3864f9458fd4ea534f4af6a"
metafile = true
