name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5468689adc9413694a5592ec003608503d65d14a2eee8cabe6264bb5181f9ca"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
