name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a58736e3a89821d0caca013ecb380ab14a08a5969727a669f80e0a2e2f87f6"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
