name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe5b105f409537ef4c918f3413542be0813373160dd68efa52cc65613fc4e9f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
