name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3e7fe724e46b87af0c0d98afcf0bb6c3769276d13edf3c2988a0ffd75bacb69"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
