name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d305f6c182c6ca4574d546d96481bb1bc7f315573a3c307f60728902de9af0b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
