name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8764ddc55a27ff094f0f111aee82f48fbd78149c1ca4f7bfd7b0454ed4e9deb0"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
