name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4f343dde01d37c15aa39df9b829c336a8a93d7fc9c158fa3128cfa9a89a1515"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
