name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fd9d2c2a9999afb2d34a2901c5ad909fa869259130f0b730015478ce660c998"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
