name = "LWCraft"
author = "Le0nWolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08500c99ce03f516a74fb605730d4fa7b2e7ada12015abbe74095cdebef29767"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
